kind: pipeline
type: docker
name: default

steps:
- name: test
  image: mjehanno/golang_gui_linux:latest
  commands:
  - go test ./...
  - go test ./... -json > test-report.out
  - go test ./... -coverprofile=cover.out
- name: code-analysis
  image: aosapps/drone-sonar-plugin
  settings:
    sonar_host:
      from_secret: sonar_host
    sonar_token:
      from_secret: sonar_token
- name: build
  image: mjehanno/golang_gui_linux:latest
  commands:
    - go build .
- name: package android
  image: mjehanno/golang_gui_android:latest
  commands:
  - go get fyne.io/fyne/v2
  - fyne package -os android -appID $APP_ID -icon $ICON_PATH
- name: package linx
  image: mjehanno/golang_gui_linux:latest
  commands:
  - go get fyne.io/fyne/v2
  - fyne package -os linux -icon $ICON_PATH
  environment:
    APP_ID: com.mjehanno.dnd-spellcounter
    ICON_PATH: ./Icon.png
  when: 
    event:
    - tag
- name: publish
  image: plugins/github-release
  settings:
    api_key: api_token
    files: fyne-cross/bin/*
    title: DRONE_TAG
  when:
    event: 
    - tag

    
